name: car_rental
description: A new Flutter project.


publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter


 
  cupertino_icons: ^1.0.2
  flutter_bloc: ^7.3.1
  equatable: ^2.0.3
  get_it: ^7.2.0
  pluto_grid: 2.10.3
  responsive_table: ^0.2.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4


flutter:

  
  uses-material-design: true

  
  assets:
    - assets/images/
    - assets/fonts/
    - assets/i18n/


  fonts:
    - family: Saira
      fonts:
        - asset: assets/fonts/Saira_Expanded-ExtraBold.ttf
          weight: 900
        - asset: assets/fonts/SairaCondensed-Black.ttf
          weight: 900
        - asset: assets/fonts/SairaCondensed-ExtraBold.ttf
          weight: 900
        - asset: assets/fonts/SairaCondensed-Bold.ttf
        - asset: assets/fonts/SairaCondensed-Semibold.ttf
        - asset: assets/fonts/SairaCondensed-Medium.ttf
        - asset: assets/fonts/SairaCondensed-Regular.ttf
        - asset: assets/fonts/SairaCondensed-Light.ttf
        - asset: assets/fonts/SairaCondensed-ExtraLight.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
